services:
  elk-es:
    container_name: elk-es
    image: elasticsearch:7.7.0
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx1024m"
    volumes:
      # data
      - ./data/es/plugins:/usr/share/elasticsearch/plugins
      - ./data/es/data:/usr/share/elasticsearch/data
      - ./data/es/logs:/usr/share/elasticsearch/logs
      # config
      - ./conf/es.yaml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - '9200:9200'
    restart: always

  elk-kibana:
    container_name: elk-kibana
    image: kibana:7.7.0
    volumes:
      - ./conf/kibana.yaml:/usr/share/kibana/config/kibana.yml:ro
    ports:
      - '5601:5601'
    restart: always

  elk-logstash:
    container_name: elk-logstash
    image: logstash:7.7.0
    volumes:
      - ./conf/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
      - ./conf/logstash.yaml:/usr/share/logstash/config/logstash.yml
      - /var/lib/docker/containers/:/docker-log/:ro
    ports:
      - '127.0.0.1:5140:5140'
    restart: always

  elk-nginx-demo:
    container_name: elk-nginx-demo
    image: nginx:latest
    ports:
      - '8099:80'
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://127.0.0.1:5140"
        tag: "elk-nginx-demo"
    restart: always
